variables:
  GIT_SUBMODULE_STRATEGY: recursive

gcc:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=g++
  artifacts:
    paths:
      - "bean-*"

clang:
  image: inf4/luci:ubuntu-jammy
  script:
    - make CXX=clang++
  artifacts:
    paths:
      - "bean-*"

style:
  image: inf4/luci:ubuntu-jammy
  script:
    - make lint
    - make tidy
